box_name = $(notdir $(CURDIR))
reg := sroegner
tag := "$(reg)/$(box_name)"

OS := $(shell uname -s)
ifeq ($(OS),Darwin)
  DOCKER_CMD := docker
  IP := $$(echo $(DOCKER_HOST)|sed 's%tcp://\(.*\)\:.*%\1%g')
else
  DOCKER_CMD := sudo docker
  EXECUTOR_NUMBER?=0
  LAST_OCTET := $$(expr $(EXECUTOR_NUMBER) + 10)
  IP         := 127.10.10.$(LAST_OCTET)
endif

CIDFILE := $(CURDIR)/$(box_name)-$(IP).container.id

