EXECUTOR_NUMBER?=0
DOCKER_CMD := docker
box_name = $(notdir $(CURDIR))
USER := $(shell id -un)
container_name = $(box_name)-$(USER)-$(EXECUTOR_NUMBER)
reg := sroegner
tag := $(reg)/$(box_name)
thirdoctet ?= 10
OS := $(shell uname -s)

ifeq ($(OS),Darwin)
  IP := $$(echo $(DOCKER_HOST)|sed 's%tcp://\(.*\)\:.*%\1%g')
else
  LAST_OCTET := $$(expr $(EXECUTOR_NUMBER) + 10)
  IP         := 127.10.$(thirdoctet).$(LAST_OCTET)
endif

